AWSTemplateFormatVersion: 2010-09-09
Description: Mappings Example Demo

Parameters:
  MyKeyName:
    Description: Select the Key Name
    Type: AWS::EC2::KeyPair::KeyName
  MyEnvironment:
    Description: Select the Environment
    ConstraintDescription: Environment should be either dev or prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Mappings: 
  MyRegionMap:
    eu-west-1:
      AMIID: ami-0ee415e1b8b71305f
    eu-west-2:
      AMIID: ami-04706e771f950937f
  MyEnvironmentMap:
    dev:
      instanceType: t1.micro
    prod:
      instanceType: t2.micro

Conditions:
  ProdOnlyEIP:
    Fn::Equals:
      - !Ref MyEnvironment
      - prod
      
Resources: 
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref MyKeyName
      ImageId: !FindInMap 
        - MyRegionMap
        - !Ref 'AWS::Region'
        - AMIID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironment
        - instanceType
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: ProdOnlyEIP
    Properties:
      InstanceId: !Ref MyEC2Instance
  

   